#pragma once
#include <LovyanGFX.hpp>
#include <vector>
#include "../helper.h"

// Individual ring within a Ripple effect
struct RippleRing {
    float currentRadius;
    float currentIntensity;
    float targetRadius;
    // Track edges to prevent infinite bouncing
    float edgeL, edgeR, edgeT, edgeB; 
};

class Ripple {
    public:
        Ripple(float x, float y, float intensity, float initialRadius = 0);
        
        // Returns false if all rings have faded
        bool update(); 
        void draw(LGFX_Sprite* sprite);
        
        // Returns a vector of NEW ripples generated by bouncing
        std::vector<Ripple> detectBouncing(int width, int height);

        // Getters for collision detection
        float getX() const { return x_; }
        float getY() const { return y_; }
        const std::vector<RippleRing>& getRings() const { return rings_; }

    private:
        float x_, y_;
        float maxIntensity_;
        float speed_;
        
        // Spawning logic
        unsigned long startMillis_;
        int remainingRipples_;
        unsigned long interval_ = 150; // ms between rings

        std::vector<RippleRing> rings_;
};